# Setup Dapr (Microservices, StateStore, PubSub, Bindings)

# Setup LinkedIn DataHub (Metadata, Lineage, Disovery)

# Setup Kafka (PubSub)

# Setup MongoDB (DataStore)

# Setup Neo4j (DataStore)

# Setup PostgeSQL (DataStore)

# Setup Spark (Distributed Processing)
