Name: Contoso University Data Product File
Description: A data product to query and manage students and courses at the Contoso University.
Release: v0.0.0

License:
  Name: MIT
  Url: https://opensource.org/licenses/MIT

Owner:
  Name: Test User
  Email: test@email.com
  Organisation: Test Org
  Phone: "+4512345678"
  Website: https://test-site.com

FeatureFlags:
  EnableInputs: true
  EnableOutputs: true

Apis:
  Rest:
    EnableBulkController: true

Inputs:
  - Type: File
    FilePath: assets/input/contoso-university-single.json
  - Type: File
    FilePath: assets/input/contoso-university-multiple.json

Outputs:
  - Type: File
    FilePath: assets/output/contoso-university-single.txt