Name: Contoso University Data Product
Description: A data product to query and manage students and courses at the Contoso University.
Version: v0.0.1

License:
  Name: MIT
  Url: https://opensource.org/licenses/MIT

Owner:
  Name: Test User
  Email: test@email.com
  Organisation: Test Org
  Phone: "+4512345678"
  Website: https://test-site.com

FeatureFlags:
  EnableDashboard: true
  EnableApis:
    - Rest
    - GraphQL
  EnableCaching: true
  EnableDataIngestion: true
  EnableDataCatalog: false
  EnableDataEgestion: false # TODO: #143 Enable feature gated data publication with configured pub/sub
  EnableTracing: false # TODO: #141 Enable feature gated tracing with OpenTelemetry and Jaeger
  EnableMetrics: false # TODO: #140 Enable feature gated metrics with Prometheus and Grafana
  EnableAuthentication: false # TODO: #138 Enable feature gated authentication with Duende IdentityServer and OpenID Connect
  EnableAuthorisation: false # TODO: #137 Enable feature gated authorisation with Duende IdentityServer and OpenID Connect
  EnableWebhooks: false # TODO: Enable feature gated webhooks

DataStore:
  Type: SQL
  Provider: Sqlite
  ConnectionString: Data Source=sqlite.db

CacheStore:
  Type: InMemory

SchemaRegistry:
  Type: Local
  Schema:
    Subject: contoso-university
    Version: 1

DataIngestors:
  - Type: Local
    FilePath: assets/data/contoso-university-single.json
  - Type: Local
    FilePath: assets/data/contoso-university-multiple.json
