domain:
    name: Students
    description: A data product to query and manage students and courses at SDU.
    version: v0.1

owner:
    name: Nikolai Emil Damm

schemas:
    - name: Student
      version: v0.1
      properties:
          - name: Name
            type: string
          - name: Age
            type: number
          - name: Courses
            type: Course[]
          - name: Grades
            type: number[]
          - name: FavoriteCourse
            type: Course
    - name: Course
      version: v0.1
      properties:
          - name: Name
            type: string
          - name: Credits
            type: number

features:
  apis: 
    - graphql
    - rest
  database: relational
  caching: false
  metadata: false
  authentication: false
  authorization: false
  metrics: false
  tracing: false
  health: false
  logging: false

# authorization:
#     ClientID: ""
#     ClientSecret: ""
#     Scopes: []
#     AuthorizationURL: ""
#     TokenURL: ""
