DataProduct:
  Name: Students Data Product
  Version: v0.0.1
  FeatureFlags:
    EnableApis:
      - Rest
      - GraphQL
    EnableDataIngestion: true
  Services:
    DataStore:
      Type: SQL
      Provider: Sqlite
      ConnectionString: Data Source=sqlite.db
    SchemaRegistry:
      Type: Local
      Schema:
        Subject: contoso-university-single
        Version: 1
    DataIngestionSources:
      - Type: Local
        FilePath: assets/data/contoso-university-single-value.json
