name: Build and Test Data Mesh
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  DOTNET_VERSION: 7.0.x
  NUGET_FEED: https://nuget.pkg.github.com/devantler/index.json
  NUGET_USER: devantler

jobs:
  build-and-test:
    runs-on: macos-latest # TODO: fix build on ubuntu-latest.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK v${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Add NuGet Source
        run: dotnet nuget add source --username $NUGET_USER --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "${{ env.NUGET_FEED }}"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" --configuration Release --no-build

      - name: Upload Code Coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: tests/**/TestResults/**/coverage.cobertura.xml
          fail_ci_if_error: true
